spring:
  application:
    name: TokenProject
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1004

server:
  port: 9091


mybatis:
  mapper-locations: classpath:mappers/*.xml

jwt:
  issuer: dddodo1004@naver.com
  secret_key: X4DdojBpj1F5xYgHjUQz3xdQmasDvWsGtan6/iPE1L7QLEePfbtnGUks+wPmHVJLv/7mlEDgQg+Me4dZ6tivZQ==